# This file was generated by the cucumber:install task before, but now
# I have to add this manually

When /^I go to (.*)$/ do |page_name|
  visit path_to(page_name)
end

Then /^(?:|I )should (?:|still )be on (.+)$/ do |page_name|
  current_path.should == path_to(page_name)
end

Then /^(?:|I )should be redirected to (.+)$/ do |page_name|
  current_path.should == path_to(page_name)
end

Then /^(?:|I )should see message "([^"]*)"$/ do |text|
  if page.respond_to? :should
    page.should have_content(text)
  else
    assert page.has_content?(text)
  end
end
